creditCardType:
  silver:
    interestRate: 10
    oneTimeLimit: 10000
    monthlyLimit: 100000
  gold:
    interestRate: 9
    oneTimeLimit: 20000
    monthlyLimit: 200000
  platinum:
    interestRate: 8
    oneTimeLimit: 30000
    monthlyLimit: 300000